=== opendatalabcz/opendata/src/main/resources/xsd/datasource_mapping.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="property" type="recordProperty"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="recordProperty">
            <xs:sequence>
                <xs:element name="sourceFileColumn" minOccurs="0" maxOccurs="unbounded" type="sourceColumn"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="converter" type="xs:string" use="optional"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="sourceColumn">
        <xs:attribute name="originalName" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="argumentName" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== opendatalabcz/opendata/src/main/resources/mappings/mocr/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>4</headerRow>

        <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>

        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="id" argumentName="authorityIdentifier"/>
        </retriever>

        <property name="authorityRole" value="CUSTOMER" onlyNewRecords="true"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="id" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="IČO dodavatele" argumentName="ico"/>
            <sourceFileColumn originalName="Úredni název &quot;dodavatele&quot;" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Název VZ" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Smluvni cena bez DPH" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mocr.MOContractDateSetter">
            <sourceFileColumn originalName="Datum uzavreni smlouvy" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mdcr/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>
        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="CISLO" argumentName="authorityIdentifier"/>
        </retriever>
        <propertySet ref="all"/>
    </mappedSheet>

    <propertySet name="all">
        <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="CISLO" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="DODAVATEL" argumentName="name"/>
            <sourceFileColumn originalName="ICDOD" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="PREDMET" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="CENA" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.mdcr.MDDateCreatedSetter">
            <sourceFileColumn originalName="PLATOD" argumentName="dateFrom"/>
            <sourceFileColumn originalName="DATUCIN" argumentName="dateInEffect"/>
            <sourceFileColumn originalName="DATPOD" argumentName="dateSubmitted"/>
            <sourceFileColumn originalName="CISLO" argumentName="authorityIdentifier"/>
        </property>

        <property name="dateOfExpiry" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="PLATDO" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </propertySet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mpo/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mpo.MPOInvoiceRetriever">
            <sourceFileColumn originalName="Řada dokladů" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Evidenční číslo" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.SplitIdentifierSetter">
            <sourceFileColumn originalName="Řada dokladů" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Evidenční číslo" argumentName="serialNumber"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Název obchodního partnera" argumentName="name"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Variabilní symbol" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Fakturováno Kč" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Datum přijetí" argumentName="inputDate"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Datum splatnosti" argumentName="inputDate"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Datum úhrady" argumentName="inputDate"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Předmět fakturace" argumentName="inputString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/justice/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>1</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.justice.JusticeInvoiceRecordRetriever">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="DŘ" argumentName="categoryCode"/>
            <sourceFileColumn originalName="č. dokladu" argumentName="serialNumber"/>
            <sourceFileColumn originalName="Č. dokladu" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.TripleSplitIdentifierSetter">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="DŘ" argumentName="categoryCode"/>
            <sourceFileColumn originalName="č. dokladu" argumentName="serialNumber"/>
            <sourceFileColumn originalName="Č. dokladu" argumentName="serialNumber"/>
        </property>

        <property name="authorityRole" value="CUSTOMER" onlyNewRecords="true"/>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="IČ" argumentName="ico"/>
            <sourceFileColumn originalName="Dodavatel" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.SubjectCategorySetter">
            <sourceFileColumn originalName="rozp. položka" argumentName="inputNumber"/>
            <sourceFileColumn originalName="Rozp.položka" argumentName="inputNumber"/>
            <sourceFileColumn originalName="Obsah" argumentName="inputString"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Variabilní symbol" argumentName="inputString"/>
        </property>


        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Zapsáno" argumentName="inputDateString"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Splatnost" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Uhrazeno" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mmr/czt/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>
        <retriever className="eu.profinit.opendata.transform.convert.mmr.czt.CZTInvoiceRetriever">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo dokladu" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.TripleSplitIdentifierSetter">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo dokladu" argumentName="serialNumber"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Osoba" argumentName="name"/>
        </property>

        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mmr.czt.DirectStringSemicolonTrimSetter">
            <sourceFileColumn originalName="Popis" argumentName="inputString"/>
            <sourceFileColumn originalName="Popis;" argumentName="inputString"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" required="false" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Datum příchodu" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" required="false" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Datum úhrady" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mfcr/mapping-old-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <headerRow>0</headerRow>

    <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
        <sourceFileColumn originalName="Číslo faktury" argumentName="authorityIdentifier"/>
    </retriever>

    <property name="recordType" onlyNewRecords="true" value="INVOICE"/>

    <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Účel platby" argumentName="inputString"/>
    </property>

    <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
        <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
    </property>

    <property name="originalCurrencyAmount" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectMoneySetter">
        <sourceFileColumn originalName="Úhrada cizí měna" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
    </property>

    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Číslo faktury" argumentName="inputString"/>
    </property>

    <property name="partner" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mfcr.PartnerByCodeSetter">
        <sourceFileColumn originalName="Kód partnera" argumentName="code"/>
    </property>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Datum přijetí" argumentName="inputDate"/>
    </property>

    <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Datum splatnosti" argumentName="inputDate"/>
    </property>

    <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Datum úhrady" argumentName="inputDate"/>
    </property>

    <!-- Kazdy zaznam je nezavisly, dostane nove masterID -->
    <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>


</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mzcr/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="id" argumentName="authorityIdentifier"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="id" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="dodavatel_název" argumentName="name"/>
            <sourceFileColumn originalName="dodavatel_ičo" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="účel_platby" argumentName="inputString"/>
        </property>

        <property name="budgetCategory" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.BudgetCategoryAppender">
            <sourceFileColumn originalName="kapitola_rozpočtu" argumentName="category"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="částka_s_dph" argumentName="inputAmount"/>
        </property>

        <property name="amountCzk" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
            <sourceFileColumn originalName="částka_s_dph" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="datum_přijetí" argumentName="inputDateString"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="datum_splatnosti" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="datum_úhrady" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/justice/mapping-2015-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>1</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.justice.JusticeInvoiceRecordRetriever">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.TripleSplitIdentifierSetter">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo" argumentName="serialNumber"/>
        </property>

        <property name="authorityRole" value="CUSTOMER" onlyNewRecords="true"/>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="IČ" argumentName="ico"/>
            <sourceFileColumn originalName="Osoba" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Důvod úhrady" argumentName="inputString"/>
            <sourceFileColumn originalName="PARAMETR4" argumentName="inputString"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Variabilní symbol" argumentName="inputString"/>
        </property>


        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Zapsáno" argumentName="inputDate"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Splatnost" argumentName="inputDate"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Uhrazeno" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </mappedSheet>
</mapping>
