=== opendatalabcz/opendata/src/main/resources/xsd/datasource_mapping.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="property" type="recordProperty"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="recordProperty">
            <xs:sequence>
                <xs:element name="sourceFileColumn" minOccurs="0" maxOccurs="unbounded" type="sourceColumn"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="converter" type="xs:string" use="optional"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="sourceColumn">
        <xs:attribute name="originalName" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="argumentName" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== opendatalabcz/opendata/src/main/resources/mappings/justice/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <headerRow>0</headerRow>

    <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
        <sourceFileColumn originalName="Číslo smlouvy" argumentName="authorityIdentifier"/>
    </retriever>

    <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>

    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Číslo smlouvy" argumentName="inputString"/>
    </property>

    <property name="authorityRole" value="CUSTOMER" onlyNewRecords="true"/> <!-- This needs a converter -->

    <property name="partner" onlyNewRecords="true"
              converter="eu.profinit.opendata.transform.convert.PartnerSetter">
        <sourceFileColumn originalName="IČO" argumentName="ico"/>
        <sourceFileColumn originalName="Název smluvního partnera" argumentName="name"/>
    </property>

    <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Stručný předmět smlouvy" argumentName="inputString"/>
    </property>


    <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.justice.ContractAllAmountSetter">
        <sourceFileColumn originalName="Částka vč. DPH" argumentName="inputAmount"/>
    </property>

    <property name="inEffect" onlyNewRecords="false" value="true"/>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.justice.ContractDateCreatedSetter">
        <sourceFileColumn originalName="Číslo smlouvy" argumentName="authorityIdentifier"/>
    </property>

    <property name="dateOfExpiry" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.justice.ContractExpiryDateSetter">
        <sourceFileColumn originalName="Platnost" argumentName="inputDate"/>
    </property>

    <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

    </property>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mmr/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mmr.MMRInvoiceRetriever">
            <sourceFileColumn originalName="Osoba" argumentName="partnerName"/>
            <sourceFileColumn originalName="Částka" argumentName="amount"/>
            <sourceFileColumn originalName="Předmět fakturace" argumentName="subject"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.SplitIdentifierSetter">
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo" argumentName="serialNumber"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Osoba" argumentName="name"/>
            <sourceFileColumn originalName="IČ" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Předmět fakturace" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
             <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CzechDateSetter">
            <sourceFileColumn originalName="Datum příchodu" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CzechDateSetter">
            <sourceFileColumn originalName="Datum úhrady" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/justice/mapping-old-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>1</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.justice.JusticeInvoiceRecordRetriever">
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Dokladová řáda" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo dokladu" argumentName="serialNumber"/>
            <sourceFileColumn originalName="Číslo dokadu" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.TripleSplitIdentifierSetter">
            <sourceFileColumn originalName="Rok" argumentName="inputYear"/>
            <sourceFileColumn originalName="Dokladová řada" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Dokladová řáda" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Číslo dokladu" argumentName="serialNumber"/>
            <sourceFileColumn originalName="Číslo dokadu" argumentName="serialNumber"/>
        </property>

        <property name="authorityRole" value="CUSTOMER" onlyNewRecords="true"/>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="IČO" argumentName="ico"/>
            <sourceFileColumn originalName="IČ" argumentName="ico"/>
            <sourceFileColumn originalName="Osoba" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Důvod úhrady" argumentName="inputString"/>
            <sourceFileColumn originalName="PARAMETR4" argumentName="inputString"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Variabilní symbol" argumentName="inputString"/>
        </property>


        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
            <sourceFileColumn originalName="Částka předpis" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Datum zápisu" argumentName="inputDate"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Splatnost dne" argumentName="inputDate"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Posl. úhr. dne" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mmr/mapping-orders.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mmr.MMROrderRetriever">
            <sourceFileColumn originalName="Název/příjmení" argumentName="partnerName"/>
            <sourceFileColumn originalName="Popis" argumentName="subject"/>
            <sourceFileColumn originalName="Datum objednání" argumentName="dateCreated"/>
        </retriever>

        <property name="recordType" value="ORDER" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Číslo objednávky" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Název/příjmení" argumentName="name"/>
            <sourceFileColumn originalName="IČ" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Popis" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka v Kč" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Datum objednání" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mzp/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>3</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="Číslo smlouvy" argumentName="authorityIdentifier"/>
        </retriever>

        <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>
        <property name="inEffect" value="true" onlyNewRecords="false"/>

        <property name="authorityRole" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPRoleSetter">
            <sourceFileColumn originalName="Povaha smlouvy" argumentName="inputRole"/>
        </property>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Číslo smlouvy" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Dodavatel" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Předmět smlouvy" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPContractAmountSetter">
            <sourceFileColumn originalName="Celková částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPDateSetter">
            <sourceFileColumn originalName="Datum podpisu" argumentName="inputDate"/>
        </property>

        <property name="dateOfExpiry" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPDateSetter">
            <sourceFileColumn originalName="Datum ukončení smlouvy" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mapping-orders.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../xsd/datasource_mapping.xsd">

    <headerRow>1</headerRow>

    <property name="recordType" value="ORDER" onlyNewRecords="true"/>

    <property name="subject" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.SubjectAppender">
        <sourceFileColumn originalName="Předmět" argumentName="mainSubject"/>
        <sourceFileColumn originalName="Předmět_řádku" argumentName="lineSubject"/>
    </property>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Datum_vystavení" argumentName="inputDateString"/>
    </property>

    <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
        <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
    </property>

    <property name="originalCurrencyAmount" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectMoneySetter">
        <sourceFileColumn originalName="Částka_v_měně" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithoutVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="Částka_bez_DPH" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="Ćástka" argumentName="inputAmount"/> <!-- Ano, opravdu je tam carka misto hacku -->
    </property>

    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Číslo_objednávky" argumentName="inputString"/>
    </property>

</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mzp/mapping-csv-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="faktura" argumentName="authorityIdentifier"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="faktura" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="dodavatel" argumentName="name"/>
            <sourceFileColumn originalName="ico" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="ucel_platby" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="celkova_castka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="datum_vystaveni" argumentName="inputDate"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="datum_splatnosti" argumentName="inputDate"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="datum_uhrady" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.SubjectCategorySetter">
            <sourceFileColumn originalName="polozka_rozpoctu" argumentName="inputNumber"/>
            <sourceFileColumn originalName="nazev_plozky_rozpoctu" argumentName="inputString"/>
        </property>

        <property name="contractId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPCorrelator">
            <sourceFileColumn originalName="objednavka/smlouva" argumentName="contractId"/>
        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mk/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>
        <retriever className="eu.profinit.opendata.transform.convert.mk.MKContractRetriever">
            <sourceFileColumn originalName="Číslo smlouvy" argumentName="authorityIdentifier"/>
            <sourceFileColumn originalName="Název partnera" argumentName="partnerName"/>
            <sourceFileColumn originalName="Předmět smlouvy" argumentName="subject"/>
            <sourceFileColumn originalName="Platnost od" argumentName="dateCreated"/>
        </retriever>
        <propertySet ref="all"/>
    </mappedSheet>

    <propertySet name="all">
        <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Číslo smlouvy" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Název partnera" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Předmět smlouvy" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Platnost od" argumentName="inputDate"/>
        </property>

        <property name="dateOfExpiry" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
            <sourceFileColumn originalName="Platnost do" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

        </property>
    </propertySet>

</mapping>
