=== opendatalabcz/opendata/src/main/resources/xsd/datasource_mapping.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="property" type="recordProperty"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="recordProperty">
            <xs:sequence>
                <xs:element name="sourceFileColumn" minOccurs="0" maxOccurs="unbounded" type="sourceColumn"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="converter" type="xs:string" use="optional"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="sourceColumn">
        <xs:attribute name="originalName" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="argumentName" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== opendatalabcz/opendata/src/main/resources/mappings/mfcr/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <headerRow>0</headerRow>

    <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
        <sourceFileColumn originalName="[CISLO]" argumentName="inputAuthorityIdentifier"/>
    </retriever>

    <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

    <property name="subject" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.SubjectAppender">
        <sourceFileColumn originalName="[UCELPLATBY]" argumentName="mainSubject"/>
        <sourceFileColumn originalName="[NAZEVPOLOZKAROZPOCTU]" argumentName="lineSubject"/>
    </property>

    <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
        <sourceFileColumn originalName="[MENA]" argumentName="inputCurrencyCode"/>
    </property>

    <property name="originalCurrencyAmount" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectMoneySetter">
        <sourceFileColumn originalName="[CELKOVACASTKACIZIMENA]" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithoutVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="[CELKOVACASTKABEZDPH]" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="[CELKOVACASTKA]" argumentName="inputAmount"/>
    </property>

    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="[CISLO]" argumentName="inputString"/>
    </property>

    <property name="partner" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.PartnerSetter">
        <sourceFileColumn originalName="[DODAVATEL]" argumentName="name"/>
        <sourceFileColumn originalName="[ICO]" argumentName="ico"/>
    </property>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="[DATUMVYSTAVENI]" argumentName="inputDateString"/>
    </property>

    <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="[DATUMSPLATNOSTI]" argumentName="inputDateString"/>
    </property>

    <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="[DATUMUHRADY]" argumentName="inputDateString"/>
    </property>

</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mfcr/mapping-orders.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <headerRow>1</headerRow>

    <property name="recordType" value="ORDER" onlyNewRecords="true"/>

    <property name="subject" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.SubjectAppender">
        <sourceFileColumn originalName="Předmět" argumentName="mainSubject"/>
        <sourceFileColumn originalName="Předmět_řádku" argumentName="lineSubject"/>
    </property>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Datum_vystavení" argumentName="inputDate"/>
    </property>

    <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
        <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
    </property>

    <property name="originalCurrencyAmount" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectMoneySetter">
        <sourceFileColumn originalName="Částka_řádku_v_měně" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithoutVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="Částka_řádku_bez_DPH" argumentName="inputAmount"/>
    </property>

    <property name="amountCzkWithVat" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
        <sourceFileColumn originalName="Částka_řádku" argumentName="inputAmount"/>
    </property>


    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Číslo_objednávky" argumentName="inputString"/>
    </property>

    <property name="partner" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.PartnerSetter">
        <sourceFileColumn originalName="Název_partnera" argumentName="name"/>
        <sourceFileColumn originalName="IČO" argumentName="ico"/>
    </property>

    <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.PropertyBasedMasterIdSetter">
        <sourceFileColumn originalName="Číslo_objednávky" argumentName="authorityIdentifier"/>
    </property>

</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mvcr/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mvcr.MVInvoiceRetriever">
            <sourceFileColumn originalName="cislo_dokladu" argumentName="authorityIdentifier"/>
            <sourceFileColumn originalName="castka" argumentName="amount"/>
            <sourceFileColumn originalName="jmeno_firmy" argumentName="partnerName"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="cislo_dokladu" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true" required="false"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="jmeno_firmy" argumentName="name"/>
            <sourceFileColumn originalName="ico" argumentName="ico"/>
        </property>

        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="kod_meny" argumentName="inputCurrencyCode"/>
        </property>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="castka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="datum_uctovani" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mfcr/mapping-contracts.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <headerRow>1</headerRow>

    <property name="recordType" value="CONTRACT" onlyNewRecords="true"/>

    <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
        <sourceFileColumn originalName="Číslo_smlouvy/dodatku" argumentName="authorityIdentifier"/>
    </retriever>

    <property name="authorityRole" onlyNewRecords="true" 
              converter="eu.profinit.opendata.transform.convert.mfcr.ContractRoleConverter">
        <sourceFileColumn originalName="Povaha_smlouvy" argumentName="role"/>
    </property>

    <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
        <sourceFileColumn originalName="Číslo_smlouvy/dodatku" argumentName="inputString"/>
    </property>

    <property name="partner" onlyNewRecords="true"
              converter="eu.profinit.opendata.transform.convert.PartnerSetter">
        <sourceFileColumn originalName="IČO" argumentName="ico"/>
        <sourceFileColumn originalName="Název_partnera" argumentName="name"/>
    </property>

    <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.SubjectAppender">
        <sourceFileColumn originalName="Popis_smluvního_typu" argumentName="mainSubject"/>
        <sourceFileColumn originalName="Předmět" argumentName="lineSubject"/>
    </property>
    
    <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
        <sourceFileColumn originalName="Měna" argumentName="inputCurrencyCode"/>
    </property>

    <property name="originalCurrencyAmount" onlyNewRecords="false"
              converter="eu.profinit.opendata.transform.convert.mfcr.ContractAmountSetter">
        <sourceFileColumn originalName="Částka" argumentName="contractAmount"/>
        <sourceFileColumn originalName="Částka01" argumentName="invoiceAmount"/>
    </property>

    <property name="inEffect" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mfcr.ContractValiditySetter">
        <sourceFileColumn originalName="Kód_stavu" argumentName="validity"/>
    </property>

    <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Platnost_od" argumentName="inputDateString"/>
    </property>
    
    <property name="dateOfExpiry" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DateSetter">
        <sourceFileColumn originalName="Platnost_do" argumentName="inputDateString"/>
    </property>

    <property name="parentRecord" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mfcr.ContractParentSetter">
        <sourceFileColumn originalName="Typ_smlouvy" argumentName="type"/>
    </property>
    
    <property name="invoiceId" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.mfcr.ContractAndInvoiceCorrelator">
        <sourceFileColumn originalName="Číslo_faktury" argumentName="invoiceId"/>
    </property>

    <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter">

    </property>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mzp/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>3</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.PropertyBasedRecordRetriever">
            <sourceFileColumn originalName="Číslo faktury" argumentName="authorityIdentifier"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Číslo faktury" argumentName="inputString"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Dodavatel" argumentName="name"/>
            <sourceFileColumn originalName="ICO" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Popis" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Celková částka" argumentName="inputAmount"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPDateSetter">
            <sourceFileColumn originalName="Datum platby" argumentName="inputDate"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

        <property name="contractId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mzp.MZPCorrelator">
            <sourceFileColumn originalName="Číslo smlouvy" argumentName="contractId"/>
        </property>
    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mmr/sfrb/mapping-2018-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>3</headerRow>
        <retriever className="eu.profinit.opendata.transform.convert.YearAppenderRetriever">
            <sourceFileColumn originalName="Řada dokladů" argumentName="categoryType"/>
            <sourceFileColumn originalName="Evidenční číslo" argumentName="serialNumber"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true"
                  converterParameter="2018" converter="eu.profinit.opendata.transform.convert.YearAppenderIdentificationSetter">
            <sourceFileColumn originalName="Řada dokladů" argumentName="categoryCode"/>
            <sourceFileColumn originalName="Evidenční číslo" argumentName="serialNumber"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Název obchodního partnera" argumentName="name"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Předmět" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="Celkem Kč" argumentName="inputAmount"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Variabilní symbol" argumentName="inputString"/>
        </property>

        <property name="dateCreated" required="false" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Datum přijetí" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" required="false" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Datum úhrady" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mmr/crr/mapping-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">
        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mmr.crr.CRRInvoiceRetriever">
            <sourceFileColumn originalName="Řada" argumentName="categoryType"/>
            <sourceFileColumn originalName="Poř.č." argumentName="serialNumber"/>
            <sourceFileColumn originalName="Datum případu (DMR)" argumentName="date"/>
        </retriever>

        <property name="recordType" value="INVOICE" onlyNewRecords="true"/>

        <property name="authorityRole" onlyNewRecords="true" value="CUSTOMER"/>

        <property name="authorityIdentifier" onlyNewRecords="true"
                  converterParameter="2019" converter="eu.profinit.opendata.transform.convert.DateCategorySetter">
            <sourceFileColumn originalName="Řada" argumentName="categoryType"/>
            <sourceFileColumn originalName="Poř.č." argumentName="serialNumber"/>
            <sourceFileColumn originalName="Datum případu (DMR)" argumentName="date"/>
        </property>

        <property name="partner" onlyNewRecords="true"
                  converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Název" argumentName="name"/>
            <sourceFileColumn originalName="IČO" argumentName="ico"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="Poznámka 2 - 255" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" value="CZK"/>

        <property name="allAmounts" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.AllAmountSetter">
            <sourceFileColumn originalName="HM celkem po zaokrouhlení" argumentName="inputAmount"/>
        </property>

        <property name="dateOfPayment" required="false" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="Datum úhrady (DMR)" argumentName="inputDateString"/>
        </property>

        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>
</mapping>

=== opendatalabcz/opendata/src/main/resources/mappings/mk/mapping-csv-invoices.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../xsd/datasource_mapping.xsd">

    <mappedSheet number="0">

        <headerRow>0</headerRow>

        <retriever className="eu.profinit.opendata.transform.convert.mk.MKCsvInvoiceRetriever">
            <sourceFileColumn originalName="DatumPrijeti" argumentName="dateCreated"/>
            <sourceFileColumn originalName="Rozliseni" argumentName="inputType"/>
            <sourceFileColumn originalName="Cislo" argumentName="record"/>
        </retriever>

        <property name="authorityIdentifier" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.YearTypeNumberIdentifierSetter">
            <sourceFileColumn originalName="DatumPrijeti" argumentName="dateCreated"/>
            <sourceFileColumn originalName="Rozliseni" argumentName="inputType"/>
            <sourceFileColumn originalName="Cislo" argumentName="record"/>
        </property>

        <property name="recordType" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.mk.TypeSetter">
            <sourceFileColumn originalName="Rozliseni" argumentName="inputType"/>
        </property>

        <property name="subject" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="UcelPlatby" argumentName="inputString"/>
        </property>

        <property name="budgetCategory" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.mk.BudgetStringSetter">
            <sourceFileColumn originalName="Stredisko" argumentName="departmentOld"/>
            <sourceFileColumn originalName="KodStredisko" argumentName="departmentNumber"/>
            <sourceFileColumn originalName="NazevStredisko" argumentName="departmentString"/>
            <sourceFileColumn originalName="KodRozpPolozka" argumentName="inputItemNumber"/>
            <sourceFileColumn originalName="NazevRozpPolozka" argumentName="inputItemString"/>
        </property>

        <property name="variableSymbol" onlyNewRecords="false" converter="eu.profinit.opendata.transform.convert.DirectStringSetter">
            <sourceFileColumn originalName="VS" argumentName="inputString"/>
        </property>

        <property name="currency" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CurrencySetter">
            <sourceFileColumn originalName="Mena" argumentName="inputCurrencyCode"/>
        </property>

        <property name="originalCurrencyAmount" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.DirectMoneySetter">
            <sourceFileColumn originalName="Uhrada" argumentName="inputAmount"/>
        </property>

        <property name="amountCzk" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.CZKAmountSetter">
            <sourceFileColumn originalName="Uhrada" argumentName="inputAmount"/>
        </property>

        <property name="partner" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.PartnerSetter">
            <sourceFileColumn originalName="Dodavatel" argumentName="name"/>
            <sourceFileColumn originalName="IcDodavatele" argumentName="ico"/>
        </property>

        <property name="dateCreated" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="DatumPrijeti" argumentName="inputDateString"/>
        </property>

        <property name="dueDate" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="DatumSplatnosti" argumentName="inputDateString"/>
        </property>

        <property name="dateOfPayment" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.UniversalDateSetter">
            <sourceFileColumn originalName="DatumUhrady" argumentName="inputDateString"/>
        </property>

        <!-- Kazdy zaznam je nezavisly, dostane nove masterID -->
        <property name="masterId" onlyNewRecords="true" converter="eu.profinit.opendata.transform.convert.RandomMasterIdSetter"/>

    </mappedSheet>

</mapping>
